### ISSUE TITLE
Icons are too small

### ISSUE THREAD

**Issue by AdrienLemaire** [Ferdi265/numix-solarized-gtk-theme#26]
Screenshot of the application mypaint v1.2.1 on arch linux
![](https://i.imgur.com/cAoBfsB.png)

As far as I understand, we do not have any control on [the icon sizes](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-icon-sizes) since GTK 3.10 (now on GTK 3.24).

I cannot figure out how to make my icons larger. Also, I wonder why the submenu has a dark background when it should be light. All the Numix solarized light variants seem to have this issue.

Any idea how to fix this issue?

.config/gtk-3.0/settings.ini
```ini
[Settings]
gtk-theme-name=NumixSolarizedLightYellow
gtk-icon-theme-name=Numix-Light
gtk-font-name=Hack 16
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
gtk-application-prefer-dark-theme=false
gtk-decoration-layout=menu
```

.config/gtk-3.0/gtk.css
```css

/* Always use background color */
GtkWindow {
    background-color: @theme_bg_color;
}

/* Fix tooltip background override */
.tooltip {
    background-color: rgba(0, 0, 0, 0.8);
}

.tooltip * {
    background-color: transparent;
}

/* Fix Nautilus desktop window background override */
NautilusWindow {
     background-color: transparent;
 }
```
